name: Upload to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip the tasks folder
        run: zip -r tasks.zip tasks/

      - name: Upload tasks.zip to S3
        run: aws s3 cp tasks.zip s3://sportsbettingoddspredictionpipeline/dags/tasks.zip

      - name: Upload Dockerfile to S3
        run: aws s3 cp Dockerfile s3://sportsbettingoddspredictionpipeline/build/Dockerfile

      - name: Upload entrypoint.sh to S3
        run: aws s3 cp entrypoint.sh s3://sportsbettingoddspredictionpipeline/build/entrypoint.sh
